// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: geegee.proto

package geegeepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 上报时的 Unix 时间戳毫秒
	// 包含的各类度量数据 (边缘聚合后)
	Cpu  *CPUSummary  `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem  *MemSummary  `protobuf:"bytes,4,opt,name=mem,proto3" json:"mem,omitempty"`
	Disk *DiskSummary `protobuf:"bytes,5,opt,name=disk,proto3" json:"disk,omitempty"`
	Net  *NetSummary  `protobuf:"bytes,6,opt,name=net,proto3" json:"net,omitempty"`
	Kvm  *KVMSummary  `protobuf:"bytes,7,opt,name=kvm,proto3" json:"kvm,omitempty"`
	// 网络连通性探测测算结果
	PingResults   []*PingResult `protobuf:"bytes,8,rep,name=ping_results,json=pingResults,proto3" json:"ping_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_geegee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReportRequest) GetCpu() *CPUSummary {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *ReportRequest) GetMem() *MemSummary {
	if x != nil {
		return x.Mem
	}
	return nil
}

func (x *ReportRequest) GetDisk() *DiskSummary {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *ReportRequest) GetNet() *NetSummary {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *ReportRequest) GetKvm() *KVMSummary {
	if x != nil {
		return x.Kvm
	}
	return nil
}

func (x *ReportRequest) GetPingResults() []*PingResult {
	if x != nil {
		return x.PingResults
	}
	return nil
}

type CPUSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Mhz           float64                `protobuf:"fixed64,3,opt,name=mhz,proto3" json:"mhz,omitempty"`
	UsagePerc     []float64              `protobuf:"fixed64,4,rep,packed,name=usage_perc,json=usagePerc,proto3" json:"usage_perc,omitempty"`
	Load1         float64                `protobuf:"fixed64,5,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5         float64                `protobuf:"fixed64,6,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15        float64                `protobuf:"fixed64,7,opt,name=load15,proto3" json:"load15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUSummary) Reset() {
	*x = CPUSummary{}
	mi := &file_geegee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUSummary) ProtoMessage() {}

func (x *CPUSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUSummary.ProtoReflect.Descriptor instead.
func (*CPUSummary) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{1}
}

func (x *CPUSummary) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CPUSummary) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPUSummary) GetMhz() float64 {
	if x != nil {
		return x.Mhz
	}
	return 0
}

func (x *CPUSummary) GetUsagePerc() []float64 {
	if x != nil {
		return x.UsagePerc
	}
	return nil
}

func (x *CPUSummary) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *CPUSummary) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *CPUSummary) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

type MemSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Available     uint64                 `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Used          uint64                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	UsedPercent   float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	SwapTotal     uint64                 `protobuf:"varint,5,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapFree      uint64                 `protobuf:"varint,6,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemSummary) Reset() {
	*x = MemSummary{}
	mi := &file_geegee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemSummary) ProtoMessage() {}

func (x *MemSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemSummary.ProtoReflect.Descriptor instead.
func (*MemSummary) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{2}
}

func (x *MemSummary) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemSummary) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemSummary) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemSummary) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *MemSummary) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MemSummary) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

type DiskSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReadBytes      uint64                 `protobuf:"varint,1,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes     uint64                 `protobuf:"varint,2,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	ReadCount      uint64                 `protobuf:"varint,3,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	WriteCount     uint64                 `protobuf:"varint,4,opt,name=write_count,json=writeCount,proto3" json:"write_count,omitempty"`
	IopsInProgress uint64                 `protobuf:"varint,5,opt,name=iops_in_progress,json=iopsInProgress,proto3" json:"iops_in_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DiskSummary) Reset() {
	*x = DiskSummary{}
	mi := &file_geegee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskSummary) ProtoMessage() {}

func (x *DiskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskSummary.ProtoReflect.Descriptor instead.
func (*DiskSummary) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{3}
}

func (x *DiskSummary) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskSummary) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *DiskSummary) GetReadCount() uint64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *DiskSummary) GetWriteCount() uint64 {
	if x != nil {
		return x.WriteCount
	}
	return 0
}

func (x *DiskSummary) GetIopsInProgress() uint64 {
	if x != nil {
		return x.IopsInProgress
	}
	return 0
}

type NetSummary struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	BytesRecv   uint64                 `protobuf:"varint,1,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	BytesSent   uint64                 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	PacketsRecv uint64                 `protobuf:"varint,3,opt,name=packets_recv,json=packetsRecv,proto3" json:"packets_recv,omitempty"`
	PacketsSent uint64                 `protobuf:"varint,4,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	// 高级突发网络特征
	MicroburstEvents uint64  `protobuf:"varint,5,opt,name=microburst_events,json=microburstEvents,proto3" json:"microburst_events,omitempty"`
	BurstP95Rate     float64 `protobuf:"fixed64,6,opt,name=burst_p95_rate,json=burstP95Rate,proto3" json:"burst_p95_rate,omitempty"` // 例如 p95 的发包/收包率极值
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetSummary) Reset() {
	*x = NetSummary{}
	mi := &file_geegee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetSummary) ProtoMessage() {}

func (x *NetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetSummary.ProtoReflect.Descriptor instead.
func (*NetSummary) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{4}
}

func (x *NetSummary) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *NetSummary) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NetSummary) GetPacketsRecv() uint64 {
	if x != nil {
		return x.PacketsRecv
	}
	return 0
}

func (x *NetSummary) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *NetSummary) GetMicroburstEvents() uint64 {
	if x != nil {
		return x.MicroburstEvents
	}
	return 0
}

func (x *NetSummary) GetBurstP95Rate() float64 {
	if x != nil {
		return x.BurstP95Rate
	}
	return 0
}

type KVMSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalVms       int32                  `protobuf:"varint,1,opt,name=total_vms,json=totalVms,proto3" json:"total_vms,omitempty"`
	ActiveVms      int32                  `protobuf:"varint,2,opt,name=active_vms,json=activeVms,proto3" json:"active_vms,omitempty"`
	TotalAllocVcpu int32                  `protobuf:"varint,3,opt,name=total_alloc_vcpu,json=totalAllocVcpu,proto3" json:"total_alloc_vcpu,omitempty"`
	TotalAllocMem  uint64                 `protobuf:"varint,4,opt,name=total_alloc_mem,json=totalAllocMem,proto3" json:"total_alloc_mem,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KVMSummary) Reset() {
	*x = KVMSummary{}
	mi := &file_geegee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVMSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVMSummary) ProtoMessage() {}

func (x *KVMSummary) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVMSummary.ProtoReflect.Descriptor instead.
func (*KVMSummary) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{5}
}

func (x *KVMSummary) GetTotalVms() int32 {
	if x != nil {
		return x.TotalVms
	}
	return 0
}

func (x *KVMSummary) GetActiveVms() int32 {
	if x != nil {
		return x.ActiveVms
	}
	return 0
}

func (x *KVMSummary) GetTotalAllocVcpu() int32 {
	if x != nil {
		return x.TotalAllocVcpu
	}
	return 0
}

func (x *KVMSummary) GetTotalAllocMem() uint64 {
	if x != nil {
		return x.TotalAllocMem
	}
	return 0
}

type PingResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetIp       string                 `protobuf:"bytes,1,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetPort     int32                  `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	MinRttMs       float64                `protobuf:"fixed64,3,opt,name=min_rtt_ms,json=minRttMs,proto3" json:"min_rtt_ms,omitempty"`
	MaxRttMs       float64                `protobuf:"fixed64,4,opt,name=max_rtt_ms,json=maxRttMs,proto3" json:"max_rtt_ms,omitempty"`
	AvgRttMs       float64                `protobuf:"fixed64,5,opt,name=avg_rtt_ms,json=avgRttMs,proto3" json:"avg_rtt_ms,omitempty"`
	PacketLossRate float64                `protobuf:"fixed64,6,opt,name=packet_loss_rate,json=packetLossRate,proto3" json:"packet_loss_rate,omitempty"` // 丢包率 0.0 - 1.0
	TargetType     string                 `protobuf:"bytes,7,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`                 // tcpping, icmp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_geegee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{6}
}

func (x *PingResult) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *PingResult) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *PingResult) GetMinRttMs() float64 {
	if x != nil {
		return x.MinRttMs
	}
	return 0
}

func (x *PingResult) GetMaxRttMs() float64 {
	if x != nil {
		return x.MaxRttMs
	}
	return 0
}

func (x *PingResult) GetAvgRttMs() float64 {
	if x != nil {
		return x.AvgRttMs
	}
	return 0
}

func (x *PingResult) GetPacketLossRate() float64 {
	if x != nil {
		return x.PacketLossRate
	}
	return 0
}

func (x *PingResult) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

// ReportResponse 主控端针对探针流返回的下发指令或确认
type ReportResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 留给将来动态下发网络质量探测的目标（比如让节点执行对某个 IP 的 TCPPing）
	ProbeTargets  []*ProbeTarget `protobuf:"bytes,3,rep,name=probe_targets,json=probeTargets,proto3" json:"probe_targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_geegee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{7}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResponse) GetProbeTargets() []*ProbeTarget {
	if x != nil {
		return x.ProbeTargets
	}
	return nil
}

type ProbeTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // e.g., "tcpping", "icmp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTarget) Reset() {
	*x = ProbeTarget{}
	mi := &file_geegee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTarget) ProtoMessage() {}

func (x *ProbeTarget) ProtoReflect() protoreflect.Message {
	mi := &file_geegee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTarget.ProtoReflect.Descriptor instead.
func (*ProbeTarget) Descriptor() ([]byte, []int) {
	return file_geegee_proto_rawDescGZIP(), []int{8}
}

func (x *ProbeTarget) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ProbeTarget) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProbeTarget) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

var File_geegee_proto protoreflect.FileDescriptor

const file_geegee_proto_rawDesc = "" +
	"\n" +
	"\fgeegee.proto\x12\vgeegeepb.v1\"\xdc\x02\n" +
	"\rReportRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12)\n" +
	"\x03cpu\x18\x03 \x01(\v2\x17.geegeepb.v1.CPUSummaryR\x03cpu\x12)\n" +
	"\x03mem\x18\x04 \x01(\v2\x17.geegeepb.v1.MemSummaryR\x03mem\x12,\n" +
	"\x04disk\x18\x05 \x01(\v2\x18.geegeepb.v1.DiskSummaryR\x04disk\x12)\n" +
	"\x03net\x18\x06 \x01(\v2\x17.geegeepb.v1.NetSummaryR\x03net\x12)\n" +
	"\x03kvm\x18\a \x01(\v2\x17.geegeepb.v1.KVMSummaryR\x03kvm\x12:\n" +
	"\fping_results\x18\b \x03(\v2\x17.geegeepb.v1.PingResultR\vpingResults\"\xb6\x01\n" +
	"\n" +
	"CPUSummary\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x10\n" +
	"\x03mhz\x18\x03 \x01(\x01R\x03mhz\x12\x1d\n" +
	"\n" +
	"usage_perc\x18\x04 \x03(\x01R\tusagePerc\x12\x14\n" +
	"\x05load1\x18\x05 \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\x06 \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\a \x01(\x01R\x06load15\"\xb3\x01\n" +
	"\n" +
	"MemSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x04R\tavailable\x12\x12\n" +
	"\x04used\x18\x03 \x01(\x04R\x04used\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x05 \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_free\x18\x06 \x01(\x04R\bswapFree\"\xb7\x01\n" +
	"\vDiskSummary\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x01 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x02 \x01(\x04R\n" +
	"writeBytes\x12\x1d\n" +
	"\n" +
	"read_count\x18\x03 \x01(\x04R\treadCount\x12\x1f\n" +
	"\vwrite_count\x18\x04 \x01(\x04R\n" +
	"writeCount\x12(\n" +
	"\x10iops_in_progress\x18\x05 \x01(\x04R\x0eiopsInProgress\"\xe3\x01\n" +
	"\n" +
	"NetSummary\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x01 \x01(\x04R\tbytesRecv\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x12!\n" +
	"\fpackets_recv\x18\x03 \x01(\x04R\vpacketsRecv\x12!\n" +
	"\fpackets_sent\x18\x04 \x01(\x04R\vpacketsSent\x12+\n" +
	"\x11microburst_events\x18\x05 \x01(\x04R\x10microburstEvents\x12$\n" +
	"\x0eburst_p95_rate\x18\x06 \x01(\x01R\fburstP95Rate\"\x9a\x01\n" +
	"\n" +
	"KVMSummary\x12\x1b\n" +
	"\ttotal_vms\x18\x01 \x01(\x05R\btotalVms\x12\x1d\n" +
	"\n" +
	"active_vms\x18\x02 \x01(\x05R\tactiveVms\x12(\n" +
	"\x10total_alloc_vcpu\x18\x03 \x01(\x05R\x0etotalAllocVcpu\x12&\n" +
	"\x0ftotal_alloc_mem\x18\x04 \x01(\x04R\rtotalAllocMem\"\xef\x01\n" +
	"\n" +
	"PingResult\x12\x1b\n" +
	"\ttarget_ip\x18\x01 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\x05R\n" +
	"targetPort\x12\x1c\n" +
	"\n" +
	"min_rtt_ms\x18\x03 \x01(\x01R\bminRttMs\x12\x1c\n" +
	"\n" +
	"max_rtt_ms\x18\x04 \x01(\x01R\bmaxRttMs\x12\x1c\n" +
	"\n" +
	"avg_rtt_ms\x18\x05 \x01(\x01R\bavgRttMs\x12(\n" +
	"\x10packet_loss_rate\x18\x06 \x01(\x01R\x0epacketLossRate\x12\x1f\n" +
	"\vtarget_type\x18\a \x01(\tR\n" +
	"targetType\"\x83\x01\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\rprobe_targets\x18\x03 \x03(\v2\x18.geegeepb.v1.ProbeTargetR\fprobeTargets\"R\n" +
	"\vProbeTarget\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType2\\\n" +
	"\fProbeService\x12L\n" +
	"\rReportMetrics\x12\x1a.geegeepb.v1.ReportRequest\x1a\x1b.geegeepb.v1.ReportResponse(\x010\x01B2Z0github.com/geelinx-ltd/geegee/api/proto;geegeepbb\x06proto3"

var (
	file_geegee_proto_rawDescOnce sync.Once
	file_geegee_proto_rawDescData []byte
)

func file_geegee_proto_rawDescGZIP() []byte {
	file_geegee_proto_rawDescOnce.Do(func() {
		file_geegee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geegee_proto_rawDesc), len(file_geegee_proto_rawDesc)))
	})
	return file_geegee_proto_rawDescData
}

var file_geegee_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_geegee_proto_goTypes = []any{
	(*ReportRequest)(nil),  // 0: geegeepb.v1.ReportRequest
	(*CPUSummary)(nil),     // 1: geegeepb.v1.CPUSummary
	(*MemSummary)(nil),     // 2: geegeepb.v1.MemSummary
	(*DiskSummary)(nil),    // 3: geegeepb.v1.DiskSummary
	(*NetSummary)(nil),     // 4: geegeepb.v1.NetSummary
	(*KVMSummary)(nil),     // 5: geegeepb.v1.KVMSummary
	(*PingResult)(nil),     // 6: geegeepb.v1.PingResult
	(*ReportResponse)(nil), // 7: geegeepb.v1.ReportResponse
	(*ProbeTarget)(nil),    // 8: geegeepb.v1.ProbeTarget
}
var file_geegee_proto_depIdxs = []int32{
	1, // 0: geegeepb.v1.ReportRequest.cpu:type_name -> geegeepb.v1.CPUSummary
	2, // 1: geegeepb.v1.ReportRequest.mem:type_name -> geegeepb.v1.MemSummary
	3, // 2: geegeepb.v1.ReportRequest.disk:type_name -> geegeepb.v1.DiskSummary
	4, // 3: geegeepb.v1.ReportRequest.net:type_name -> geegeepb.v1.NetSummary
	5, // 4: geegeepb.v1.ReportRequest.kvm:type_name -> geegeepb.v1.KVMSummary
	6, // 5: geegeepb.v1.ReportRequest.ping_results:type_name -> geegeepb.v1.PingResult
	8, // 6: geegeepb.v1.ReportResponse.probe_targets:type_name -> geegeepb.v1.ProbeTarget
	0, // 7: geegeepb.v1.ProbeService.ReportMetrics:input_type -> geegeepb.v1.ReportRequest
	7, // 8: geegeepb.v1.ProbeService.ReportMetrics:output_type -> geegeepb.v1.ReportResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_geegee_proto_init() }
func file_geegee_proto_init() {
	if File_geegee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geegee_proto_rawDesc), len(file_geegee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geegee_proto_goTypes,
		DependencyIndexes: file_geegee_proto_depIdxs,
		MessageInfos:      file_geegee_proto_msgTypes,
	}.Build()
	File_geegee_proto = out.File
	file_geegee_proto_goTypes = nil
	file_geegee_proto_depIdxs = nil
}
